org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Confirma estes 4 valores em https://fabricmc.net/develop (escolhe 1.21.11)
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.4
loader_version=0.18.4
loom_version=1.14-SNAPSHOT

mod_version=1.0.0
maven_group=app.ghostclient
archives_base_name=ghostclient
